---
title: "Instituto Nacional de Estadística"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    css: style.css
    orientation: rows
    vertical_layout: fill
    social: menu
    logo: ine_logo.svg
    favicon: ine_logo.svg
    source_code: "https://github.com/walkerke/neighborhood_diversity"


---

```{r,echo=FALSE}
knitr::opts_chunk$set( cache= FALSE)

```

```{r eval=FALSE}
library(flexdashboard)
library(shinydashboard)

articles = function() return(45)
valueBox(articles, icon = "fa-pencil")
```



```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(shiny)
#library(ggplot2)
library(flexdashboard)

#library(mgcv)
library(dplyr)
library(plotly)
library(ineapir)
#library(tidyverse)
#library(highcharter)


# Obtener ids y nombres
ids = get_metadata_table_varval(25143) %>% 
  filter(Fk_Variable %in% c(70, 349)) %>%
  pull(Id)

nombres = get_metadata_table_varval(25143) %>%
  filter(Fk_Variable %in% c(70, 349)) %>%
  pull(Nombre)

# Crear estructura para el selectInput
selector_lugar <- setNames(ids, nombres)

# Filtro para obtener datos
filter_ecoicop_1 <- list(
  "762" = "",        # Todos los GRUPOS de 2 dígitos del ECOICOP
  "3" = "72",        # Dato Base
  "57" = "8859"      # Gasto medio por persona
)

# Obtenemos datos
data_ecoicop_1 <- get_data_table(
  filter = filter_ecoicop_1, idTable = 25143, # nlast = 1,
  tip = "AM",  unnest = TRUE, metacodes = TRUE, validate = FALSE, metanames = TRUE
)

#colnames(data_ecoicop_1)

```


Sidebar {.sidebar}
=======================================================================


### Filtrado


```{r}


selectInput('x', 'Ambito geográfico', choices = selector_lugar,selected =9002 )
selectInput('anyo', 'Año', choices = as.character(seq(2010,2022,1)),selected =2022 )



jj <- reactive({ data_ecoicop_1 %>%
    filter(Comunidad.autónoma.de.residencia.Id == as.character(input$x)) %>%
        filter(Anyo== input$anyo) %>%
     mutate(parents=c("", rep("Índice general", length(`Grupos.de.gasto.(2.dígitos)`) - 1)))
})
```



Dashboard
=======================================================================

```{r echo=FALSE}

#get_metadata_table_varval(10262)

filter_poblacion<-list("18" = "451", # Ambos sexos
                       "356" = "15668", # Todos los años
                       "349" = "16473", # Total Nacional
                       "70"= "") # Todas ccaa
                       
data_poblacion<-get_data_table(filter = filter_poblacion,idTable = 10262,tip = "AM",metanames = TRUE,metacodes = TRUE, unnest = TRUE)


data_poblacion$Fecha<-format(as.Date(data_poblacion$Fecha),"%m")
data_poblacion<-data_poblacion%>% 
  filter(Fecha== "01")


data_poblacion2<-reactive({as.numeric(data_poblacion %>% 
  filter(Anyo== input$anyo) %>% 
    filter(`Comunidades.y.ciudades.autónomas.Id` == as.character(input$x)) %>% select(Valor)) })


# Ahora aqui sueldo medio

filter_dist<-list(
  "18"="451", # Sexo=Ambos Sexos
  "647"="298419", # Media
  "349"="16473", # Total nacional
  "70"="" # Todas comunidades autónomas
)


data_dist<-get_data_table(idTable = 28191,tip="AM",filter=filter_dist,nlast = 1,unnest=TRUE,metanames = TRUE,metacodes = TRUE)%>% select("Comunidades.autónomas.Id","Anyo","Valor")


data_dist_reactive<-reactive({as.numeric(data_dist %>% 
  filter(Anyo== input$anyo) %>% 
    filter(`Comunidades.autónomas.Id` == as.character(input$x)) %>% select(Valor)) })









```


Row
-----------------------------------------------------------------------

###  {.value-box}


```{r}
renderValueBox({
    rate <- formatC(data_poblacion2(), digits = 0,format="f", big.mark = ".",decimal.mark = ",")
 shinydashboard::valueBox(rate, "Habitantes", icon = icon("person"))})
```

### {.value-box}

```{r}
renderValueBox({
   rate <- paste0(formatC(data_dist_reactive(), digits = 2,format="f", big.mark = ".",decimal.mark = ",")," €")
 shinydashboard::valueBox(rate, "Sueldo bruto medio", icon = icon("coins"))})
```
###  {.value-box}

```{r}
 valueBox(10 * 2, "New Orders", icon = icon("trash"))
```

Row
-----------------------------------------------------------------------


###  {data-width=700}

```{r,eval=FALSE}

# Etiquetas


#  data_ecoicop_1<-data_ecoicop_1[data_ecoicop_1$Comunidad.autónoma.de.residencia=="Canarias",]



```



Distribución el gasto medio por persona en España dentro de los grupos ECOICOP:



```{r}

output$scatter <- renderPlotly({
 g <- plot_ly(jj(),
  type = "treemap",
  labels =  ~`Grupos.de.gasto.(2.dígitos)`,
  parents = ~ parents,
  values = ~Valor ,
    maxdepth = 2,
    branchvalues='total',
  tiling = list(squarifyratio = 2))
})  

plotlyOutput('scatter')




```



### Habitantes {data-width=340}



```{r}
library(leaflet)
library(sf)
# Filtrar por esperanza de vida
# "" para indicar que tome todos los valores
#get_metadata_table_varval(13930)

filter2 = list( 
  "349"="16473", #Total nacional
  "120" = "10758", # Jornada a tiempo completo
   "70" = "",      # Todas ccaa
  "684" = "298931" # Total decil
  )

# Tabl de mortalidad por año, ccaa, ciudadaes, sexo, edad y funciones. 
# Table url: https://www.ine.es/jaxiT3/Tabla.htm?t=27154&L=0
esp2 <- get_data_table(idTable = 13930, filter = filter2, nlast = 1, unnest = TRUE,
                       metacodes = TRUE, tip = "AM", validate = FALSE)

# Seleccionamos columnas de interés
esp2 <- subset(esp2, select = c("Comunidades.y.Ciudades.Autonómas.Id","Anyo","Valor"))


```





```{r}

# Contornos de las ccaa
ccaa2 <- read_sf("https://www.ine.es/wstempus/geojs/ES/CONTORNOS/70")

```


  
  

```{r, warning=FALSE}

# join de los contornos y el dataset
ccaa2 <- merge(ccaa2, esp2, by.x = "id_region", 
              by.y = "Comunidades.y.Ciudades.Autonómas.Id" )

world <- reactive({ ccaa2 %>%
    filter(id_region == as.character(input$x)) 
})



# Creamos colores para cada rango de esperanza de vida
pal2 <- colorNumeric("plasma",domain= NULL)

# Labels of the map


# Create the map
output$map <- renderLeaflet({
  m2 <- leaflet(world()) %>% 
  addProviderTiles(providers$Esri.WorldImagery) %>%
  setView(-4, 40, zoom = 5) %>%
  addPolygons(fillOpacity = 0.8,
              fillColor = ~pal2(Valor),
              weight = 1,
              color = "white",
              highlightOptions = highlightOptions(fillOpacity = 1, bringToFront = TRUE, 
                                                  weight = 2, color = "white"))
})
leafletOutput('map')  

```


```{r,eval=FALSE}
# Creamos colores para cada rango de esperanza de vida
pal2 <- colorNumeric("plasma",domain= NULL)

# Labels of the map
labels <- sprintf(
  "<strong>%s</strong><br/> Sueldo bruto mensual %s € ",
  ccaa2$nom_region, format(ccaa2$Val, big.mark = ".", decimal.mark = ",", nsmall = 2)
) %>% lapply(htmltools::HTML)


# Create the map
leaflet(ccaa2) %>% 
  addProviderTiles(providers$Esri.WorldImagery) %>%
  setView(-4, 40, zoom = 5) %>%
  addPolygons(fillOpacity = 0.8,
              fillColor = ~pal2(Valor),
              weight = 1,
              color = "white",
              label = labels,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal", padding = "3px 8px"),
                textsize = "15px",
                direction = "auto"
              ),
              highlightOptions = highlightOptions(fillOpacity = 1, bringToFront = TRUE, 
                                                  weight = 2, color = "white"))


```

